"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { PaymentPreparation } from "@/components/payment-preparation";
import type { Order } from "@/lib/data";
export default function OrderDetail() { const { id } = useParams<{ id: string }>(); const { user, loading: authLoading } = useAuth(); const router = useRouter(); const [order, setOrder] = useState<Order | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); useEffect(() => { if (!authLoading && !user) { router.replace(`/login?next=/orders/${id}`); return; } if (user) getSupabaseBrowserClient().from("orders").select("*, listings(*), seller:profiles!orders_seller_id_fkey(id,username,avatar_url,bio,created_at,wallet_address)").eq("id", id).single().then(({ data, error: e }) => { if (e) setError("Order not found or unavailable."); else setOrder(data as Order); setLoading(false); }); }, [id, user, authLoading, router]); if (authLoading || loading || !user) return <main className="mx-auto max-w-3xl px-5 py-24 text-center text-zinc-500">Loading order...</main>; if (!order) return <main className="mx-auto max-w-3xl px-5 py-24 text-center text-zinc-400">{error}</main>; return <main className="mx-auto max-w-3xl px-5 py-14"><Link href="/orders" className="text-sm text-zinc-500 hover:text-electric">← Back to orders</Link><p className="mt-8 text-xs font-bold uppercase tracking-[.2em] text-electric">Payment preparation</p><h1 className="mt-3 text-4xl font-semibold">{order.listings?.title || "Order"}</h1><p className="mt-3 text-sm text-zinc-500">Seller: {order.seller?.username || "—"} · Order status: {order.status}</p><PaymentPreparation amount={Number(order.amount_usdc)} sellerWallet={(order.seller as Order["seller"] & { wallet_address?: string } | null)?.wallet_address} /></main>; }
