import Link from "next/link";
import { AuthProvider, useAuth } from "@/components/auth-provider";

export function Logo() { return <Link href="/" className="flex items-center gap-2 font-bold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-lg bg-electric text-ink font-black">L</span><span className="text-lg">lootly<span className="text-electric">.</span></span></Link>; }
function AccountMenu() { const { user, loading, signOut } = useAuth(); if (loading) return <span className="text-sm text-zinc-500">...</span>; if (!user) return <><Link href="/login" className="hidden text-sm text-zinc-400 hover:text-white sm:block">Log in</Link><Link href="/signup" className="rounded-full bg-electric px-4 py-2 text-sm font-semibold text-ink">Sign up</Link></>; return <div className="flex items-center gap-3"><Link href="/dashboard" className="hidden text-sm text-zinc-400 hover:text-white sm:block">Dashboard</Link><button onClick={signOut} className="text-sm text-zinc-400 hover:text-white">Log out</button></div>; }
export function Header() { return <header className="border-b border-line/70"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><Logo /><nav className="hidden items-center gap-8 text-sm text-zinc-400 md:flex"><Link className="hover:text-white" href="/browse">Browse</Link><Link className="hover:text-white" href="/sell">Sell</Link><Link className="hover:text-white" href="/#how-it-works">How it works</Link></nav><div className="flex items-center gap-4"><AccountMenu /><button className="hidden rounded-full border border-line bg-white/[.04] px-4 py-2 text-sm font-medium hover:border-electric hover:text-electric lg:block">Connect wallet</button></div></div></header>; }
export function Footer() { return <footer className="border-t border-line/70"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 px-5 py-10 text-sm text-zinc-500 sm:flex-row"><div><Logo /><p className="mt-3">The marketplace for gamers.</p></div><div className="flex gap-6"><Link href="/browse" className="hover:text-white">Browse</Link><Link href="/sell" className="hover:text-white">Sell</Link><span>© 2024 Lootly</span></div></div></footer>; }
export function Button({ children, className = "", ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { children: React.ReactNode }) { return <button className={`rounded-full bg-electric px-5 py-3 font-semibold text-ink transition hover:bg-[#d9ff94] disabled:cursor-not-allowed disabled:opacity-50 ${className}`} {...props}>{children}</button>; }
export function AppShell({ children }: { children: React.ReactNode }) { return <AuthProvider>{children}</AuthProvider>; }
