"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import type { Order } from "@/lib/data";
const statuses=["pending","processing","delivered","completed"];
function Badge({status}:{status:string}){return <span className="rounded-full bg-electric/10 px-3 py-1 text-xs capitalize text-electric">{status}</span>}
export default function Orders(){const {user,loading:authLoading}=useAuth();const router=useRouter();const [orders,setOrders]=useState<Order[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");useEffect(()=>{if(!authLoading&&!user){router.replace("/login?next=/orders");return;}if(user)getSupabaseBrowserClient().from("orders").select("*, listings(*), seller:profiles!orders_seller_id_fkey(id,username,avatar_url,bio,created_at)").eq("buyer_id",user.id).order("created_at",{ascending:false}).then(({data,error:e})=>{if(e)setError(e.message);else setOrders((data as Order[])||[]);setLoading(false);});},[user,authLoading,router]);if(authLoading||!user)return <main className="mx-auto max-w-6xl px-5 py-24 text-center text-zinc-500">Loading orders...</main>;return <main className="mx-auto max-w-6xl px-5 py-14"><p className="text-xs font-bold uppercase tracking-[.2em] text-electric">Buyer hub</p><h1 className="mt-3 text-5xl font-semibold">Your orders.</h1><p className="mt-4 text-zinc-400">Track every simulated purchase in one place.</p>{loading?<p className="py-20 text-center text-zinc-500">Loading orders...</p>:error?<p className="mt-8 rounded-xl border border-red-400/30 p-4 text-red-300">{error}</p>:orders.length===0?<div className="mt-10 rounded-2xl border border-dashed border-line p-12 text-center text-zinc-500">You have no orders yet. <Link href="/browse" className="text-electric">Browse accounts →</Link></div>:<div className="mt-10 space-y-3">{orders.map(o=><div key={o.id} className="flex flex-col gap-4 rounded-2xl border border-line bg-panel p-5 md:flex-row md:items-center md:justify-between"><div><div className="flex flex-wrap items-center gap-3"><h2 className="font-semibold">{o.listings?.title||"Listing"}</h2><Badge status={o.status}/></div><p className="mt-2 text-sm text-zinc-500">{o.listings?.game} · ${o.amount_usdc} USDC · Seller: {o.seller?.username||"—"}</p><p className="mt-1 text-xs text-zinc-600">{new Date(o.created_at).toLocaleDateString()}</p></div><Link href={`/orders/${o.id}`} className="rounded-full border border-line px-4 py-2 text-center text-sm hover:border-electric">View order</Link></div>)}</div>}</main>}
