"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useSearchParams, useRouter } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { ListingCard } from "@/components/listing-card";
import type { Listing } from "@/lib/data";
export default function Dashboard() { const { user, loading: authLoading } = useAuth(); const router = useRouter(); const params = useSearchParams(); const [listings, setListings] = useState<Listing[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); useEffect(() => { if (!authLoading && !user) router.replace("/login?next=/dashboard"); if (user) getSupabaseBrowserClient().from("listings").select("*, profiles(id, username, avatar_url, bio, created_at)").eq("seller_id", user.id).order("created_at", { ascending: false }).then(({ data, error: queryError }) => { if (queryError) setError(queryError.message); else setListings((data as Listing[]) || []); setLoading(false); }); }, [authLoading, user, router]); if (authLoading || !user) return <main className="mx-auto max-w-7xl px-5 py-24 text-center text-zinc-500">Loading your dashboard...</main>; const active = listings.filter(x => x.status === "active"); const sold = listings.filter(x => x.status === "sold"); return <main className="mx-auto max-w-7xl px-5 py-14"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-electric">Seller hub</p><h1 className="mt-3 text-5xl font-semibold tracking-tight">Your dashboard.</h1></div><Link href="/sell" className="rounded-full bg-electric px-5 py-3 text-center text-sm font-semibold text-ink">＋ New listing</Link></div>{params.get("created") && <p className="mt-8 rounded-xl border border-electric/30 bg-electric/5 p-4 text-sm text-electric">Your listing was published successfully.</p>}{error && <p className="mt-8 text-red-300">Could not load your listings: {error}</p>}<div className="mt-10 grid gap-4 sm:grid-cols-3"><div className="stat"><p>Active listings</p><strong>{active.length}</strong></div><div className="stat"><p>Sold listings</p><strong>{sold.length}</strong></div><div className="stat"><p>Total earnings</p><strong>— <small>USDC</small></strong></div></div><div className="mt-14 flex items-center justify-between"><h2 className="text-2xl font-semibold">My listings</h2><span className="text-sm text-zinc-500">{listings.length} total</span></div>{loading ? <p className="py-16 text-zinc-500">Loading listings...</p> : listings.length === 0 ? <div className="mt-6 rounded-2xl border border-dashed border-line p-12 text-center text-zinc-500">You have no listings yet. <Link href="/sell" className="text-electric">Create your first one →</Link></div> : <div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{listings.map(x => <ListingCard key={x.id} listing={x}/>)}</div>}</main>; }
